### ISSUE TITLE
GitHub found potential security vulnerabilities in your dependencies

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-automated-upcoming-event-notifications#3]
Some of the dependencies defined in package-lock.json have known security vulnerabilities and should be updated. 

Please see the notification here for more details:
https://github.com/eventespresso/eea-automated-upcoming-event-notifications

**Comment by nerrad** [comment]
So, there is boilerplate code I added to every plugin to make it easier to quickly ramp up developing with the new javascript in the plugin.  The upside is we can get ramped up more quickly when/if we need to use javascript.  The downside is for add-ons that don't get attention that much, the javascript boilerplate is not kept up to date.

Currently, this new javascript boilerplate is not used by this plugin as there are no assets built with it. Thus even though github is (rightly) warning about vulnerabilities, those vulnerabilities will not get exposed because we aren't building anything with these packages.  The boilerplate code is removed on release builds so it won't even be a problem in release builds.

So, what should the next steps be?  We can do one of two things:

1. Remove the boilerplate and just take the time to add it back in when needed.  The only benefit to this is it removes the github warning.  **Note** this warning only appears for those with write access to the repository... so there's no public facing warning.
2. Leave the boilerplate.  All packages/warnings etc will get removed when the boilerplate is updated at the point it gets used.

**Comment by sethshoultes** [comment]
@nerrad I think I'm fine leaving the code for now, but just to clarify, we will need to update the boilerplate code at some point?

**Comment by nerrad** [comment]
correct.  But there's no need to do so until we actually need to implement some new javascript for the add-on (using the new js build process).  Currently the weight of what we have for boilerplate is VERY minimal because they are simply configuration files.  Github is just reading through the `package.json` file and deriving from that the security vulnerabilities.  There's actually no files installed in this repo that are vulnerable.

**Comment by nerrad** [comment]
This issue could probably be closed.
