### ISSUE TITLE
Scheduling settings per context do not seem to be followed

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-automated-upcoming-event-notifications#4]
I set the Event Admin context to Send notifications 2 days before the event. I set the Registrant context to Send notifications 3 days before the event. I set these options on Monday of this week.

The next upcoming event starts at 8:00am on September 22. I'd expect the registrant context message to send on September 19 (it did) and the event admin context to send on September 20. It did not. Instead, it was also sent on September 19, 3 minutes after the registrant context messages were sent:
![screen shot 2018-09-20 at 1 47 13 pm](https://user-images.githubusercontent.com/891156/45836788-c3954700-bcdb-11e8-8916-ec4c658f10d2.png)

**Comment by nerrad** [comment]
Spent a bit of time discussing this ticket in slack with @joshfeck and because it was a while ago this was originally reported, he's going to retest on a fresh site using the add-on.  The following things would be useful to know (assuming the issue remains).

- What cron schedules were setup and the day/time of their schedule and the recurrence period for when the schedule fires.
- The details about the event setup for the test (including datetimes info).
- Similar details as what was posted in the original report.

**Comment by joshfeck** [comment]
I'm now testing on a fresh installation and this is looking better:

![screen shot 2019-02-12 at 12 02 00 pm](https://user-images.githubusercontent.com/891156/52654300-b57cd880-2ebf-11e9-9d27-285b83d2cbf4.png)

Right now I have the admin notification set to 2 days and the registrant notification set for 3 days. It did send registrations for a events 1, 2, and 3 days out, but that's probably because I just activated all of this and it was catching up. It's significant that the 1 admin notification only mentioned events that were 2 days out. So I'm anticipating that tomorrow's admin message will mention the next upcoming event that will at that point be 2 days out.

**Comment by nerrad** [comment]
I wonder if the original report still had the old schedule of 24 hour recurrence (the current recurrence is 3 hours which was specifically supposed to resolve the original reported issue here - if I remember correctly).
